spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/reminder?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2}
    username: ${MYSQL_USERNAME:reminder}
    password: ${MYSQL_PASSWORD:reminder}
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    connect-retries: 5
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jws-algorithms: RS512

springdoc:
  swagger-ui:
    doc-expansion: none

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: framework

project:
  name: reminder
  version: 1.0.0_SNAPSHOT
  package: cc.rits.membership.console.reminder
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: infrastructure.db.entity
    client:
      package: infrastructure.db.mapper.base
      type: XMLMAPPER
    map:
      package: db.mapper.base

iam:
  url: ${IAM_URL}
  client-id: ${IAM_CLIENT_ID}
  client-secret: ${IAM_CLIENT_SECRET}

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/base/*Mapper.xml
    - classpath:/db/mapper/*Mapper.xml

logging:
  level:
    root: INFO