spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reminder?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: reminder
    password: reminder
    driver-class-name: com.mysql.cj.jdbc.Driver

iam:
  url: API_URL
  client-id: CLIENT_ID
  client-secret: CLIENT_SECRET