package cc.rits.membership.console.reminder.infrastructure.db.mapper.base;

import cc.rits.membership.console.reminder.infrastructure.db.entity.NotificationBrowsingHistory;
import cc.rits.membership.console.reminder.infrastructure.db.entity.NotificationBrowsingHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NotificationBrowsingHistoryBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    long countByExample(NotificationBrowsingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    int deleteByExample(NotificationBrowsingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    int insert(NotificationBrowsingHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    int insertSelective(NotificationBrowsingHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    List<NotificationBrowsingHistory> selectByExampleWithRowbounds(NotificationBrowsingHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    List<NotificationBrowsingHistory> selectByExample(NotificationBrowsingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") NotificationBrowsingHistory row, @Param("example") NotificationBrowsingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_browsing_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") NotificationBrowsingHistory row, @Param("example") NotificationBrowsingHistoryExample example);
}