package cc.rits.membership.console.reminder.infrastructure.db.mapper.base;

import cc.rits.membership.console.reminder.infrastructure.db.entity.NotificationReminder;
import cc.rits.membership.console.reminder.infrastructure.db.entity.NotificationReminderExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NotificationReminderBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    long countByExample(NotificationReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int deleteByExample(NotificationReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int insert(NotificationReminder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int insertSelective(NotificationReminder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    List<NotificationReminder> selectByExampleWithRowbounds(NotificationReminderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    List<NotificationReminder> selectByExample(NotificationReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    NotificationReminder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") NotificationReminder row, @Param("example") NotificationReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") NotificationReminder row, @Param("example") NotificationReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NotificationReminder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_reminder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotificationReminder row);
}