package cc.rits.membership.console.reminder.infrastructure.db.entity;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class NotificationBrowsingHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_browsing_history.notification_id
     *
     * @mbg.generated
     */
    private Integer notificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_browsing_history.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_browsing_history.viewed_date
     *
     * @mbg.generated
     */
    private LocalDateTime viewedDate;
}