name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: gradle

      - name: launch docker
        run: docker compose up -d

      - name: test
        run: |
          ./gradlew test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
